### ISSUE TITLE
Setup required tools

### ISSUE THREAD

**Issue by Eevuli** [eltsu7/transmission#2]
Tools required:
Git
Github
Zenhub
Sonarcloud
https://www.gtk.org/

**Comment by Akzuu** [comment]
Työkalut ok meikäläisellä

**Comment by mervij** [comment]
Mulla pitäis nyt myös toimia työkalut

**Comment by Eevuli** [comment]
GTKn kanssa ongelmia Windowsilla. Muuten muut toiminnassa.

**Comment by Eevuli** [comment]
Noni, nyt kaikki työkalut kunnossa myös meikäläisellä!

**Comment by eltsu7** [comment]
Jes toimii ja kääntyy

**Comment by mervij** [comment]
Mäkillä ei enää toimikaan xcodella. Nyt täytyy asentaa Linux Virtualboxin kautta.

**Comment by mervij** [comment]
Nyt toimii täälläkin, kun laittoi Linuxin...
