### ISSUE TITLE
Build source code for the first time

### ISSUE THREAD

**Issue by Eevuli** [eltsu7/transmission#4]
Kaikilla pitää saada lähdekoodi kääntymään omalla paikallisella koneella

**Comment by Akzuu** [comment]
Koodi kääntyy omassa ympäristössäni nätisti pienen säädön jälkeen

**Comment by mervij** [comment]
Mullakin kääntyy, ei mennyt ihan suorilta, mutta melkein...:)

**Comment by Eevuli** [comment]
windowsin kanssa hieman ongelmia. Jatketaan yrittämistä.

**Comment by eltsu7** [comment]
Ei buildaa windowsilla vaikka CURL asennettu:
```
-- Selecting Windows SDK version 10.0.18362.0 to target Windows 10.0.19041.
CMake Error at C:/Program Files/CMake/share/cmake-3.19/Modules/FindPackageHandleStandardArgs.cmake:218 (message):
  Could NOT find CURL (missing: CURL_LIBRARY CURL_INCLUDE_DIR) (Required is
  at least version "7.28.0")
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.19/Modules/FindPackageHandleStandardArgs.cmake:582 (_FPHSA_FAILURE_MESSAGE)
  C:/Program Files/CMake/share/cmake-3.19/Modules/FindCURL.cmake:171 (find_package_handle_standard_args)
  CMakeLists.txt:139 (find_package)
```

Selvitellään.

**Comment by Eevuli** [comment]
Asensin Ubuntun, en saanut ikinä Windowsilla toimimaan. Lopulta tuli sama Cmake error myös ubuntulla mutta sain toimimaan komennolla:
# apt-get install ca-certificates libcurl4-openssl-dev libssl-dev pkg-config build-essential checkinstall

Nyt kääntyy ja toimii, mutta vaati tosiaan Linuxin.

**Comment by eltsu7** [comment]
Linuxilla kääntyy

**Comment by mervij** [comment]
Mäkillä kääntyy edelleen, mutta ohjelman ajaminen ei onnistu, koska useampi tiedosto jostain syystä hukassa. Googlesta ei löytynyt apua. Uusi yritys Linuxilla...

**Comment by mervij** [comment]
No nyt kääntyy ja toimii Linuxilla...
